var legend = JSON.stringify(
    {
        "1": {"story": "story 1"},
        "2": {"story": "story 2"},
        "3": {"story": "story 3"},
        "4": {"story": "story 4"},
        "5": {"story": "story 5"},
        "6": {"story": "story 6"},
        "7": {"story": "story 7"},
        "8": {"story": "story 8"},
        "9": {"story": "story 9"},
        "10": {"story": "some text", "goto": 23},
        "11": {"story": "some text"},
        "17": {"story": "some text", "goto": 69},
        "20": {"story": "some text", "goto": 32},
        "27": {"story": "some text", "goto": 41},
        "28": {"story": "some text", "goto": 50},
        "37": {"story": "some text", "goto": 66},
        "45": {"story": "some text", "goto": 67},
        "46": {"story": "some text", "goto": 62},
        "54": {"story": "some text", "goto": 68},
        "60": {"story": "123", "goto": 61},
        "63": {"story": "", "goto": 2},
            "55": {"goto": 3},
            "16": {"goto": 4},
            "29": {"goto": 6},
            "24": {"goto": 7},
            "12": {"goto": 8},
            "44": {"goto": 9},
            "61": {"goto": 13},
            "52": {"goto": 35},
            "72": {"goto": 51}
    }
);